-- Run this SQL in your MySQL database to create the users table
CREATE DATABASE IF NOT EXISTS dummy ;
USE dummy;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  bio TEXT
);

CREATE TABLE IF NOT EXISTS posts (
  id INT AUTO_INCREMENT PRIMARY KEY,
 user_id int NOT NULL,
  body VARCHAR(255) NOT NULL UNIQUE,
FOREIGN KEY(user_id) REFERENCES users(id)
);
